In [ ]:
#IMPORTING REQUIRED LIBRARIES
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor


In [ ]:
df=pd.read_csv('/content/housing_data.csv')
df

House Size (sqft)  Number of Bedrooms  Number of Bathrooms  House Age  \
0         1748.357077                   1                    2       14.0   
1         1430.867849                   5                    3       91.0   
2         1823.844269                   1                    1        NaN   
3         2261.514928                   3                    1       65.0   
4         1382.923313                   2                    1       31.0   
..                ...                 ...                  ...        ...   
95         768.242526                   1                    1        9.0   
96        1648.060139                   5                    2       68.0   
97        1630.527636                   2                    2       99.0   
98        1502.556728                   2                    3       33.0   
99        1382.706433                   2                    3       51.0   

    Distance to City Center (miles)  Number of Floors         Price  
0                         17.206366                 1  255304.29450  
1                          2.820689                 2  251530.75560  
2                         15.815819                 3  173281.61860  
3                         10.051165                 1  334259.64740  
4                          5.092457                 1  207595.33830  
..                              ...               ...           ...  
95                         7.993898                 2   98831.27366  
96                        11.120462                 1  274088.04140  
97                        10.062962                 3  256548.17020  
98                        10.488380                 1  234282.19940  
99                         6.134951                 1  187076.18210  

[100 rows x 7 columns]

In [ ]:
df.head()

House Size (sqft)  Number of Bedrooms  Number of Bathrooms  House Age  \
0        1748.357077                   1                    2       14.0   
1        1430.867849                   5                    3       91.0   
2        1823.844269                   1                    1        NaN   
3        2261.514928                   3                    1       65.0   
4        1382.923313                   2                    1       31.0   

   Distance to City Center (miles)  Number of Floors        Price  
0                        17.206366                 1  255304.2945  
1                         2.820689                 2  251530.7556  
2                        15.815819                 3  173281.6186  
3                        10.051165                 1  334259.6474  
4                         5.092457                 1  207595.3383

In [ ]:
df.tail()

House Size (sqft)  Number of Bedrooms  Number of Bathrooms  House Age  \
95         768.242526                   1                    1        9.0   
96        1648.060139                   5                    2       68.0   
97        1630.527636                   2                    2       99.0   
98        1502.556728                   2                    3       33.0   
99        1382.706433                   2                    3       51.0   

    Distance to City Center (miles)  Number of Floors         Price  
95                         7.993898                 2   98831.27366  
96                        11.120462                 1  274088.04140  
97                        10.062962                 3  256548.17020  
98                        10.488380                 1  234282.19940  
99                         6.134951                 1  187076.18210

In [ ]:
df.shape

(100, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   House Size (sqft)                100 non-null    float64
 1   Number of Bedrooms               100 non-null    int64  
 2   Number of Bathrooms              100 non-null    int64  
 3   House Age                        96 non-null     float64
 4   Distance to City Center (miles)  100 non-null    float64
 5   Number of Floors                 100 non-null    int64  
 6   Price                            100 non-null    float64
dtypes: float64(4), int64(3)
memory usage: 5.6 KB


In [ ]:
df.describe()

House Size (sqft)  Number of Bedrooms  Number of Bathrooms  House Age  \
count         100.000000          100.000000           100.000000  96.000000   
mean         1448.076741            2.680000             1.950000  53.447917   
std           454.084214            1.339983             0.821123  28.797979   
min           190.127448            1.000000             1.000000   0.000000   
25%          1199.547165            1.000000             1.000000  28.750000   
50%          1436.521854            3.000000             2.000000  57.000000   
75%          1702.976026            4.000000             3.000000  75.500000   
max          2426.139092            5.000000             3.000000  99.000000   

       Distance to City Center (miles)  Number of Floors          Price  
count                       100.000000         100.00000     100.000000  
mean                         10.383505           1.81000  228659.845146  
std                           3.977190           0.82505   73158.817786  
min                           0.239561           1.00000   32166.040070  
25%                           7.398737           1.00000  188514.932150  
50%                          10.364017           2.00000  232169.267900  
75%                          13.125881           3.00000  274508.015350  
max                          20.665167           3.00000  395140.978400

In [ ]:
df.isnull().sum()

House Size (sqft)                  0
Number of Bedrooms                 0
Number of Bathrooms                0
House Age                          4
Distance to City Center (miles)    0
Number of Floors                   0
Price                              0
dtype: int64

In [ ]:
df['House Age'].fillna(df['House Age'].mean(),inplace=True)

/tmp/ipython-input-51-2188125716.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['House Age'].fillna(df['House Age'].mean(),inplace=True)


In [ ]:
#seperate featues(X) and target variable(y)
X = df.drop("Price",axis=1)
y = df["Price"]

In [ ]:
#splitting the datasets into training and datasets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
#standardise feature
Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)


In [ ]:
#create and train using LinearRegression
lr_model=LinearRegression()
lr_model.fit(X_train,y_train)

LinearRegression()

In [ ]:
#make prediction on test result- Logistics Regression
y_pred=lr_model.predict(X_test)
y_pred

array([196201.70488699, 272940.04985954, 247711.01219587, 201688.24543802,
       124740.58995227, 255301.84373434, 243948.55786881, 198009.04472739,
       184258.46157396, 243536.96972236, 145882.69927141, 231952.29265956,
       337542.81636085, 162655.53714728, 261769.12312683, 222730.58025088,
       279591.77427987, 245206.53047503, 258040.28735693, 380353.73374399])

In [ ]:
#evaluate models accuracy through R2 _score
R2_score_Lr=r2_score(y_test,y_pred)
print('Accuracy of lr ',R2_score_Lr*100)

Accuracy of lr  87.72984999113706


In [ ]:
svr_model = SVR()
svr_model.fit(X_train,y_train)

SVR()

In [ ]:
y_pred = svr_model.predict(X_test)
print(y_pred)

[232166.36517344 232169.48318916 232171.14729814 232168.87410928
 232164.4463978  232169.84634506 232171.39558466 232168.2764793
 232165.3532337  232167.96156207 232163.38448662 232168.42805563
 232173.38381655 232164.51119973 232171.18244171 232168.36985038
 232171.78770726 232170.90671639 232171.06848827 232173.76854969]


In [ ]:
#evaluate models accuracy
Accuracy_svr=r2_score(y_test,y_pred)
print('Accuracy of svr ',Accuracy_svr*100)

Accuracy of svr  -0.00281882042492132


In [ ]:
#create and train using DecisionTreeClassifier
dt_model=DecisionTreeRegressor()
dt_model.fit(X_train,y_train)

DecisionTreeRegressor()

In [ ]:
#make prediction on test result- DecisionTreeClassifier
y_pred=dt_model.predict(X_test)
y_pred

array([166846.3969 , 193309.1593 , 265319.1419 , 207069.4592 ,
        98831.27366, 302700.3366 , 302700.3366 , 234282.1994 ,
       242027.2718 , 193309.1593 , 242027.2718 , 223671.5861 ,
       346585.192  , 187650.9278 , 302700.3366 , 238448.0373 ,
       302700.3366 , 166846.3969 , 273027.6247 , 380465.4661 ])

In [ ]:
#evaluate models accuracy - DecisionTreeClassifier
Accuracy_dt=r2_score(y_test,y_pred)
print('Accuracy of DT ',Accuracy_dt*100)

Accuracy of DT  36.81866022943229


In [ ]:
#create and train using RandomForestRegressor
RF_model=RandomForestRegressor()
RF_model.fit(X_train,y_train)

RandomForestRegressor()

In [ ]:
#make prediction on test result
y_pred=RF_model.predict(X_test)
y_pred

array([211665.25846  , 210539.018652 , 245500.69387  , 210109.157073 ,
       112045.1392426, 255039.92746  , 250515.304735 , 243196.442722 ,
       205874.564177 , 224207.411457 , 182645.728988 , 218635.770266 ,
       336785.128661 , 154802.7264337, 263762.965624 , 223449.23829  ,
       259997.800912 , 212447.637585 , 243865.998395 , 341233.724971 ])

In [ ]:
#evaluate models accuracy
Accuracy_RF=r2_score(y_test,y_pred)
print('Accuracy of RF ',Accuracy_RF*100)

Accuracy of RF  70.66170980633464
